### ISSUE TITLE
Website extremely slow on Firefox

### ISSUE THREAD

**Issue by sys13** [prisma/prisma2-docs#3294] opened 2022-06-18 12:42 UTC
Please give the docs site a try on Firefox. Click around a few times. It's really slow, if functional at all

**Comment by janpio** [comment] 2022-06-18 12:53
Is it specific pages that just load longer? Or do all pages start to be slow after some while?

**Comment by ankur-arch** [comment] 2024-11-15 14:44
I'm closing this issue as we don't have sufficient info to reproduce it and have made several updates to the docs site since the creation of the issue, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏

**Closed as completed by ankur-arch** 2024-11-15 14:44 UTC
Labels: website
