### ISSUE TITLE
Scroll Restoration

### ISSUE THREAD

**Issue by broisnischal** [prisma/prisma2-docs#5572] opened 2024-01-11 09:09 UTC
Whenever I try to read through the docs when I click the next topic when being scrolled at the bottom from sidebar, it automatically scrolls me up with no reason!

**Comment by nikolasburk** [comment] 2024-11-06 10:01
Hey @broisnischal 👋  we recently rewrote our docs and I believe this should be fixed now (I couldn't reproduce it in Chrome `Version 130.0.6723.92 (Official Build) (x86_64)`)! 

If you still encounter this problem, please feel free to re-open the issue and also share with us which browser you're using 🙏

**Closed as completed by nikolasburk** 2024-11-06 10:01 UTC
Labels: website
