### ISSUE TITLE
Help article: How to migrate an implicit to an explicit m-n relation

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#4706] opened 2023-04-26 06:47 UTC
We should explain how this works based on this [Slack request](https://prisma.slack.com/archives/CA491RJH0/p1682434904417669?thread_ts=1682434578.639069&cid=CA491RJH0): 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/4058327/234492121-5dfa255d-de00-41cc-a2cf-e91b0201078d.png">

**Comment by ruheni** [comment] 2023-05-02 15:12
Closing this as it's a duplicate of #3325

**Closed as not planned by ruheni** 2023-05-02 15:12 UTC
Labels: type/docs
