### ISSUE TITLE
Issue with Prisma syntax highlighting

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma2-docs#2476] opened 2021-11-04 14:27 UTC
For example in this https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb:

![image](https://user-images.githubusercontent.com/4058327/140331765-9f3ac7dc-317a-4e4f-9adf-85d48fcb371d.png)

The fields and their types are alternating in violet and black.

**Comment by keerlu** [comment] 2022-07-21 09:27
@nilubava I closed a duplicate of this yesterday... this would be a good one to add to an upcoming sprint if possible?

(Edit: also found and closed a second duplicate... so it's popular!)

**Comment by nikolasburk** [comment] 2022-08-02 08:28
found another issue with enums [here](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#update-if-exists-or-create-a-new-user-record-with-an-email-of-aliceprismaio):

<img width="119" alt="image" src="https://user-images.githubusercontent.com/4058327/182329164-070afa9c-b738-4797-a4bf-ae777e488390.png">

**Comment by tanberry** [comment] 2022-08-02 13:54
@nilubava I failed to mention this one this morning; I know this WebDev sprint is already quite full but of things move along faster than expected, could we put this one top of list?

**Comment by nikolasburk** [comment] 2022-09-13 08:24
Found another example in the MongoDB Getting Started guide:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/4058327/189850576-d85370f1-4193-4416-81bb-7266a0589213.png">

**Comment by nikolasburk** [comment] 2022-09-13 13:48
Much better 🎉 😻

**Closed as completed** 2022-10-04 11:03 UTC
Labels: web/candidate, website
